# Generated by Django 4.0 on 2024-10-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_skill_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='users.Skill'),
        ),
    ]
