# Generated by Django 4.0 on 2024-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_skill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(default='static/deps/icons/No-image-found.svg', upload_to='media/users_images'),
        ),
    ]
