# Generated by Django 4.0 on 2024-10-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
