# Generated by Django 4.0 on 2024-10-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_transaction_user_transaction_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
