# Generated by Django 4.0 on 2024-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_user_latitude_remove_user_longitude_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
