# Generated by Django 5.1.2 on 2024-10-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
