# Generated by Django 5.1.2 on 2024-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_created_at_order_points_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_payment',
            field=models.BooleanField(default=False, verbose_name='Оплата наличными'),
        ),
    ]
